version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: tp2-postgres
    environment:
      POSTGRES_DB: apiblank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always